services:
  server:
    build: server
    ports:
      - 3000:3000
    depends_on:
      - db
    profiles:
      - backend
    environment:
      DB_HOST: db
      DB_PORT: 27017
      DB_BASE: main
  db:
    image: mongo:8-noble
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

networks:
  default:

volumes:
  data:
